package com.vamandeshmukh.demo;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import com.vamandeshmukh.demo.dtos.Book;
import com.vamandeshmukh.demo.repositories.BookRepository;

@SpringBootApplication
public class App {

	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}

@Autowired
BookRepository bookRepository;

@Bean
InitializingBean seedDatabase() {
    return () -> {
    	bookRepository.save(new Book("The Power of your Subconscious Mind",296,"Joseph Murphy","self-help",2015,5,50,"http://localhost:3006/assets/books/SELF-HELP-0001.jpg" ));
    	bookRepository.save(new Book("Great Gatsby",240,"F. Scott Fitzgerald","literature",1939,0,8,"http://localhost:3006/assets/books/LITERATURE-0002.jpg" ));
    	bookRepository.save(new Book("The Alchemist",50,"Paulo Coelho","novel",1990,0,9,"http://localhost:3006/assets/books/NOVEL-0003.jpg" ));
    	bookRepository.save(new Book("Data Smart",624,"Foreman, John","data-science",2012,0,12,"http://localhost:3006/assets/books/DATA-SCIENCE-0005.jpg" ));
    	bookRepository.save(new Book("God Created the Integers",114,"Hawking, Stephen","mathematics",2006,50,"http://localhost:3006/assets/books/MATHEMATICS-0006.jpg" ));
    	bookRepository.save(new Book("Superfreakonomics",422,"Dubner, Stephen","economics",1951,9,"http://localhost:3006/assets/books/ECONOMICS-0007.jpg" ));
    	bookRepository.save(new Book("Orientalism",269,"Said, Edward","history",1918,10,"http://localhost:3006/assets/books/HISTORY-0008.jpg" ));
    	bookRepository.save(new Book("Nature of Statistical Learning Theory, The",544,"Vapnik, Vladimir","data-science",1951,11,"http://localhost:3006/assets/books/DATA-SCIENCE-0009.jpg" ));
    	bookRepository.save(new Book("Integration of the Indian States",595,"Menon, V P","history",1918,9,"http://localhost:3006/assets/books/HISTORY-0010.jpg" ));
    	bookRepository.save(new Book("Drunkards Walk, The",653,"Mlodinow, Leonard","science",1948,12,"http://localhost:3006/assets/books/SCIENCE-0011.jpg" ));
    	bookRepository.save(new Book("Image Processing & Mathematical Morphology",585,"Shih, Frank","signal-processing",1991,11,"http://localhost:3006/assets/books/SIGNAL-PROCESSING-0012.jpg" ));
    	bookRepository.save(new Book("How to Think Like Sherlock Holmes",395,"Konnikova, Maria","psychology",2010,9,"http://localhost:3006/assets/books/PSYCHOLOGY-0013.jpg" ));
    	bookRepository.save(new Book("Data Scientists at Work",504,"Sebastian Gutierrez","data-science",1978,11,"http://localhost:3006/assets/books/DATA-SCIENCE-0014.jpg" ));
    	bookRepository.save(new Book("Slaughterhouse Five",548,"Vonnegut, Kurt","fiction",1927,10,"http://localhost:3006/assets/books/FICTION-0015.jpg" ));
    	bookRepository.save(new Book("Birth of a Theorem",596,"Villani, Cedric","mathematics",1970,12,"http://localhost:3006/assets/books/MATHEMATICS-0016.jpg" ));
    	bookRepository.save(new Book("Structure & Interpretation of Computer Programs",638,"Sussman, Gerald","computer-science",1996,11,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-0017.jpg" ));
    	bookRepository.save(new Book("Age of Wrath, The",137,"Eraly, Abraham","history",1987,9,"http://localhost:3006/assets/books/HISTORY-0018.jpg" ));
    	bookRepository.save(new Book("Trial, The",510,"Kafka, Frank","fiction",1949,10,"http://localhost:3006/assets/books/FICTION-0019.jpg" ));
    	bookRepository.save(new Book("Statistical Decision Theory",572,"Pratt, John","data-science",1999,12,"http://localhost:3006/assets/books/DATA-SCIENCE-0020.jpg" ));
    	bookRepository.save(new Book("Data Mining Handbook",230,"Nisbet, Robert","data-science",1919,12,"http://localhost:3006/assets/books/DATA-SCIENCE-0021.jpg" ));
    	bookRepository.save(new Book("New Machiavelli, The",188,"Wells, H. G.","fiction",2001,10,"http://localhost:3006/assets/books/FICTION-0022.jpg" ));
    	bookRepository.save(new Book("Physics & Philosophy",143,"Heisenberg, Werner","science",1928,9,"http://localhost:3006/assets/books/SCIENCE-0023.jpg" ));
    	bookRepository.save(new Book("Making Software",159,"Oram, Andy","computer-science",1977,11,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-0024.jpg" ));
    	bookRepository.save(new Book("Analysis, Vol I",345,"Tao, Terence","mathematics",1900,10,"http://localhost:3006/assets/books/MATHEMATICS-0025.jpg" ));
    	bookRepository.save(new Book("Machine Learning for Hackers",124,"Conway, Drew","data-science",1934,12,"http://localhost:3006/assets/books/DATA-SCIENCE-0026.jpg" ));
    	bookRepository.save(new Book("Signal and the Noise, The",411,"Silver, Nate","data-science",1931,9,"http://localhost:3006/assets/books/DATA-SCIENCE-0027.jpg" ));
    	bookRepository.save(new Book("Python for Data Analysis",318,"McKinney, Wes","data-science",1988,11,"http://localhost:3006/assets/books/DATA-SCIENCE-0028.jpg" ));
    	bookRepository.save(new Book("Introduction to Algorithms",579,"Cormen, Thomas","computer-science",1923,9,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-0029.jpg" ));
    	bookRepository.save(new Book("Beautiful and the Damned, The",568,"Deb, Siddhartha","nonfiction",1943,10,"http://localhost:3006/assets/books/NONFICTION-0030.jpg" ));
    	bookRepository.save(new Book("Outsider, The",156,"Camus, Albert","fiction",1910,11,"http://localhost:3006/assets/books/FICTION-0031.jpg" ));
    	bookRepository.save(new Book("Complete Sherlock Holmes, The - Vol I",72,"Doyle, Arthur Conan","fiction",1914,9,"http://localhost:3006/assets/books/FICTION-0032.jpg" ));
    	bookRepository.save(new Book("Complete Sherlock Holmes, The - Vol II",501,"Doyle, Arthur Conan","fiction",2005,9,"http://localhost:3006/assets/books/FICTION-0033.jpg" ));
    	bookRepository.save(new Book("Wealth of Nations, The",560,"Smith, Adam","economics",1993,12,"http://localhost:3006/assets/books/ECONOMICS-34.jpg" ));
    	bookRepository.save(new Book("Pillars of the Earth, The",377,"Follett, Ken","fiction",1979,9,"http://localhost:3006/assets/books/FICTION-35.jpg" ));
    	bookRepository.save(new Book("Mein Kampf",162,"Hitler, Adolf","nonfiction",1925,12,"http://localhost:3006/assets/books/NONFICTION-36.jpg" ));
    	bookRepository.save(new Book("Tao of Physics, The",438,"Capra, Fritjof","science",2006,10,"http://localhost:3006/assets/books/SCIENCE-37.jpg" ));
    	bookRepository.save(new Book("Surely Youre Joking Mr Feynman",179,"Feynman, Richard","science",1907,12,"http://localhost:3006/assets/books/SCIENCE-38.jpg" ));
    	bookRepository.save(new Book("Farewell to Arms, A",240,"Hemingway, Ernest","fiction",1977,11,"http://localhost:3006/assets/books/FICTION-39.jpg" ));
    	bookRepository.save(new Book("Veteran, The",479,"Forsyth, Frederick","fiction",1981,12,"http://localhost:3006/assets/books/FICTION-40.jpg" ));
    	bookRepository.save(new Book("False Impressions",320,"Archer, Jeffery","fiction",1920,11,"http://localhost:3006/assets/books/FICTION-41.jpg" ));
    	bookRepository.save(new Book("Last Lecture, The",421,"Pausch, Randy","nonfiction",1980,9,"http://localhost:3006/assets/books/NONFICTION-42.jpg" ));
    	bookRepository.save(new Book("Return of the Primitive",471,"Rand, Ayn","philosophy",1911,9,"http://localhost:3006/assets/books/PHILOSOPHY-43.jpg" ));
    	bookRepository.save(new Book("Jurassic Park",266,"Crichton, Michael","fiction",1995,10,"http://localhost:3006/assets/books/FICTION-44.jpg" ));
    	bookRepository.save(new Book("Russian Journal, A",645,"Steinbeck, John","nonfiction",1933,9,"http://localhost:3006/assets/books/NONFICTION-45.jpg" ));
    	bookRepository.save(new Book("Tales of Mystery and Imagination",293,"Poe, Edgar Allen","fiction",1975,11,"http://localhost:3006/assets/books/FICTION-46.jpg" ));
    	bookRepository.save(new Book("Freakonomics",210,"Dubner, Stephen","economics",1988,12,"http://localhost:3006/assets/books/ECONOMICS-47.jpg" ));
    	bookRepository.save(new Book("Hidden Connections, The",374,"Capra, Fritjof","science",1993,11,"http://localhost:3006/assets/books/SCIENCE-48.jpg" ));
    	bookRepository.save(new Book("Story of Philosophy, The",337,"Durant, Will","philosophy",1919,9,"http://localhost:3006/assets/books/PHILOSOPHY-49.jpg" ));
    	bookRepository.save(new Book("Asami Asami",294,"Deshpande, P L","fiction",1958,9,"http://localhost:3006/assets/books/FICTION-50.jpg" ));
    	bookRepository.save(new Book("Journal of a Novel",484,"Steinbeck, John","fiction",1952,10,"http://localhost:3006/assets/books/FICTION-51.jpg" ));
    	bookRepository.save(new Book("Once There Was a War",563,"Steinbeck, John","nonfiction",1972,11,"http://localhost:3006/assets/books/NONFICTION-52.jpg" ));
    	bookRepository.save(new Book("Moon is Down, The",442,"Steinbeck, John","fiction",1978,12,"http://localhost:3006/assets/books/FICTION-53.jpg" ));
    	bookRepository.save(new Book("Brethren, The",157,"Grisham, John","fiction",1939,10,"http://localhost:3006/assets/books/FICTION-54.jpg" ));
    	bookRepository.save(new Book("In a Free State",490,"Naipaul, V. S.","fiction",1934,9,"http://localhost:3006/assets/books/FICTION-55.jpg" ));
    	bookRepository.save(new Book("Catch 22",395,"Heller, Joseph","fiction",1902,10,"http://localhost:3006/assets/books/FICTION-56.jpg" ));
    	bookRepository.save(new Book("Complete Mastermind, The",587,"BBC","nonfiction",1939,9,"http://localhost:3006/assets/books/NONFICTION-57.jpg" ));
    	bookRepository.save(new Book("Dylan on Dylan",108,"Dylan, Bob","nonfiction",1947,9,"http://localhost:3006/assets/books/NONFICTION-58.jpg" ));
    	bookRepository.save(new Book("Soft Computing & Intelligent Systems",266,"Gupta, Madan","data-science",1909,9,"http://localhost:3006/assets/books/DATA-SCIENCE-59.jpg" ));
    	bookRepository.save(new Book("Textbook of Economic Theory",455,"Stonier, Alfred","economics",1977,10,"http://localhost:3006/assets/books/ECONOMICS-60.jpg" ));
    	bookRepository.save(new Book("Econometric Analysis",447,"Greene, W. H.","economics",1909,11,"http://localhost:3006/assets/books/ECONOMICS-61.jpg" ));
    	bookRepository.save(new Book("Learning OpenCV",448,"Bradsky, Gary","data-science",1988,11,"http://localhost:3006/assets/books/DATA-SCIENCE-62.jpg" ));
    	bookRepository.save(new Book("Data Structures Using C & C++",550,"Tanenbaum, Andrew","computer-science",1978,11,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-63.jpg" ));
    	bookRepository.save(new Book("Computer Vision, A Modern Approach",449,"Forsyth, David","data-science",1921,10,"http://localhost:3006/assets/books/DATA-SCIENCE-64.jpg" ));
    	bookRepository.save(new Book("Principles of Communication Systems",602,"Taub, Schilling","computer-science",1904,9,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-65.jpg" ));
    	bookRepository.save(new Book("Let Us C",462,"Kanetkar, Yashwant","computer-science",1980,12,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-66.jpg" ));
    	bookRepository.save(new Book("Amulet of Samarkand, The",168,"Stroud, Jonathan","fiction",1916,12,"http://localhost:3006/assets/books/FICTION-67.jpg" ));
    	bookRepository.save(new Book("Crime and Punishment",365,"Dostoevsky, Fyodor","fiction",1949,10,"http://localhost:3006/assets/books/FICTION-68.jpg" ));
    	bookRepository.save(new Book("Angels & Demons",654,"Brown, Dan","fiction",1982,9,"http://localhost:3006/assets/books/FICTION-69.jpg" ));
    	bookRepository.save(new Book("Argumentative Indian, The",329,"Sen, Amartya","nonfiction",1929,9,"http://localhost:3006/assets/books/NONFICTION-70.jpg" ));
    	bookRepository.save(new Book("Sea of Poppies",561,"Ghosh, Amitav","fiction",1936,11,"http://localhost:3006/assets/books/FICTION-71.jpg" ));
    	bookRepository.save(new Book("Idea of Justice, The",486,"Sen, Amartya","nonfiction",1938,9,"http://localhost:3006/assets/books/NONFICTION-72.jpg" ));
    	bookRepository.save(new Book("Raisin in the Sun, A",306,"Hansberry, Lorraine","fiction",1950,9,"http://localhost:3006/assets/books/FICTION-73.jpg" ));
    	bookRepository.save(new Book("All the Presidents Men",86,"Woodward, Bob","history",1933,9,"http://localhost:3006/assets/books/HISTORY-74.jpg" ));
    	bookRepository.save(new Book("Prisoner of Birth, A",672,"Archer, Jeffery","fiction",2003,11,"http://localhost:3006/assets/books/FICTION-75.jpg" ));
    	bookRepository.save(new Book("Scoop!",223,"Nayar, Kuldip","history",1997,9,"http://localhost:3006/assets/books/HISTORY-76.jpg" ));
    	bookRepository.save(new Book("Ahe Manohar Tari",79,"Deshpande, Sunita","nonfiction",2007,12,"http://localhost:3006/assets/books/NONFICTION-77.jpg" ));
    	bookRepository.save(new Book("Last Mughal, The",553,"Dalrymple, William","history",1967,10,"http://localhost:3006/assets/books/HISTORY-78.jpg" ));
    	bookRepository.save(new Book("Social Choice & Welfare, Vol 39 No. 1",532,"Various","economics",1939,12,"http://localhost:3006/assets/books/ECONOMICS-79.jpg" ));
    	bookRepository.save(new Book("Radiowaril Bhashane & Shrutika",216,"Deshpande, P L","nonfiction",1930,11,"http://localhost:3006/assets/books/NONFICTION-80.jpg" ));
    	bookRepository.save(new Book("Gun Gayin Awadi",161,"Deshpande, P L","nonfiction",1914,10,"http://localhost:3006/assets/books/NONFICTION-81.jpg" ));
    	bookRepository.save(new Book("Aghal Paghal",657,"Deshpande, P L","nonfiction",1995,11,"http://localhost:3006/assets/books/NONFICTION-82.jpg" ));
    	bookRepository.save(new Book("Maqta-e-Ghalib",170,"Garg, Sanjay","fiction",1919,9,"http://localhost:3006/assets/books/FICTION-83.jpg" ));
    	bookRepository.save(new Book("Manasa",365,"Kale, V P","nonfiction",2001,10,"http://localhost:3006/assets/books/NONFICTION-84.jpg" ));
    	bookRepository.save(new Book("India from Midnight to Milennium",571,"Tharoor, Shashi","history",1987,12,"http://localhost:3006/assets/books/HISTORY-85.jpg" ));
    	bookRepository.save(new Book("Great Indian Novel, The",129,"Tharoor, Shashi","fiction",1956,10,"http://localhost:3006/assets/books/FICTION-86.jpg" ));
    	bookRepository.save(new Book("O Jerusalem!",335,"Lapierre, Dominique","history",2000,11,"http://localhost:3006/assets/books/HISTORY-87.jpg" ));
    	bookRepository.save(new Book("City of Joy, The",198,"Lapierre, Dominique","fiction",1904,11,"http://localhost:3006/assets/books/FICTION-88.jpg" ));
    	bookRepository.save(new Book("Freedom at Midnight",520,"Lapierre, Dominique","history",1958,9,"http://localhost:3006/assets/books/HISTORY-89.jpg" ));
    	bookRepository.save(new Book("Winter of Our Discontent, The",307,"Steinbeck, John","fiction",1927,10,"http://localhost:3006/assets/books/FICTION-90.jpg" ));
    	bookRepository.save(new Book("On Education",417,"Russell, Bertrand","philosophy",1983,11,"http://localhost:3006/assets/books/PHILOSOPHY-91.jpg" ));
    	bookRepository.save(new Book("Free Will",154,"Harris, Sam","philosophy",1939,9,"http://localhost:3006/assets/books/PHILOSOPHY-92.jpg" ));
    	bookRepository.save(new Book("Bookless in Baghdad",219,"Tharoor, Shashi","nonfiction",1999,12,"http://localhost:3006/assets/books/NONFICTION-93.jpg" ));
    	bookRepository.save(new Book("Case of the Lame Canary, The",219,"Gardner, Earle Stanley","fiction",1907,9,"http://localhost:3006/assets/books/FICTION-94.jpg" ));
    	bookRepository.save(new Book("Theory of Everything, The",483,"Hawking, Stephen","science",1937,11,"http://localhost:3006/assets/books/SCIENCE-95.jpg" ));
    	bookRepository.save(new Book("New Markets & Other Essays",592,"Drucker, Peter","economics",1989,9,"http://localhost:3006/assets/books/ECONOMICS-96.jpg" ));
    	bookRepository.save(new Book("Electric Universe",428,"Bodanis, David","science",1957,12,"http://localhost:3006/assets/books/SCIENCE-97.jpg" ));
    	bookRepository.save(new Book("Hunchback of Notre Dame, The",280,"Hugo, Victor","fiction",2000,11,"http://localhost:3006/assets/books/FICTION-98.jpg" ));
    	bookRepository.save(new Book("Burning Bright",386,"Steinbeck, John","fiction",1974,9,"http://localhost:3006/assets/books/FICTION-99.jpg" ));
    	bookRepository.save(new Book("Age of Discontuinity, The",151,"Drucker, Peter","economics",1930,11,"http://localhost:3006/assets/books/ECONOMICS-100.jpg" ));
    	bookRepository.save(new Book("Doctor in the Nude",532,"Gordon, Richard","fiction",1962,9,"http://localhost:3006/assets/books/FICTION-101.jpg" ));
    	bookRepository.save(new Book("Down and Out in Paris & London",172,"Orwell, George","nonfiction",1934,9,"http://localhost:3006/assets/books/NONFICTION-102.jpg" ));
    	bookRepository.save(new Book("Identity & Violence",489,"Sen, Amartya","philosophy",2012,12,"http://localhost:3006/assets/books/PHILOSOPHY-103.jpg" ));
    	bookRepository.save(new Book("Beyond the Three Seas",440,"Dalrymple, William","history",1900,10,"http://localhost:3006/assets/books/HISTORY-104.jpg" ));
    	bookRepository.save(new Book("Talking Straight",406,"Iacoca, Lee","nonfiction",1924,9,"http://localhost:3006/assets/books/NONFICTION-105.jpg" ));
    	bookRepository.save(new Book("Maughams Collected Short Stories, Vol 3",400,"Maugham, William S","fiction",1966,12,"http://localhost:3006/assets/books/FICTION-106.jpg" ));
    	bookRepository.save(new Book("Phantom of Manhattan, The",517,"Forsyth, Frederick","fiction",1996,10,"http://localhost:3006/assets/books/FICTION-107.jpg" ));
    	bookRepository.save(new Book("Ashenden of The British Agent",500,"Maugham, William S","fiction",2003,11,"http://localhost:3006/assets/books/FICTION-108.jpg" ));
    	bookRepository.save(new Book("Zen & The Art of Motorcycle Maintenance",287,"Pirsig, Robert","philosophy",1928,9,"http://localhost:3006/assets/books/PHILOSOPHY-109.jpg" ));
    	bookRepository.save(new Book("Great War for Civilization, The",218,"Fisk, Robert","history",1920,9,"http://localhost:3006/assets/books/HISTORY-110.jpg" ));
    	bookRepository.save(new Book("We the Living",545,"Rand, Ayn","fiction",1980,9,"http://localhost:3006/assets/books/FICTION-111.jpg" ));
    	bookRepository.save(new Book("Artist and the Mathematician, The",181,"Aczel, Amir","science",1935,11,"http://localhost:3006/assets/books/SCIENCE-112.jpg" ));
    	bookRepository.save(new Book("History of Western Philosophy",363,"Russell, Bertrand","philosophy",2002,12,"http://localhost:3006/assets/books/PHILOSOPHY-113.jpg" ));
    	bookRepository.save(new Book("Rationality & Freedom",653,"Sen, Amartya","economics",1990,10,"http://localhost:3006/assets/books/ECONOMICS-114.jpg" ));
    	bookRepository.save(new Book("Clash of Civilizations and Remaking of the World Order",503,"Huntington, Samuel","history",1907,11,"http://localhost:3006/assets/books/HISTORY-115.jpg" ));
    	bookRepository.save(new Book("Uncommon Wisdom",374,"Capra, Fritjof","nonfiction",1991,12,"http://localhost:3006/assets/books/NONFICTION-116.jpg" ));
    	bookRepository.save(new Book("One",672,"Bach, Richard","nonfiction",1965,9,"http://localhost:3006/assets/books/NONFICTION-117.jpg" ));
    	bookRepository.save(new Book("To Sir With Love",318,"Braithwaite","fiction",1904,10,"http://localhost:3006/assets/books/FICTION-118.jpg" ));
    	bookRepository.save(new Book("Half A Life",603,"Naipaul, V S","fiction",1945,12,"http://localhost:3006/assets/books/FICTION-119.jpg" ));
    	bookRepository.save(new Book("Discovery of India, The",169,"Nehru, Jawaharlal","history",1923,12,"http://localhost:3006/assets/books/HISTORY-120.jpg" ));
    	bookRepository.save(new Book("Apulki",363,"Deshpande, P L","nonfiction",1909,10,"http://localhost:3006/assets/books/NONFICTION-121.jpg" ));
    	bookRepository.save(new Book("Unpopular Essays",616,"Russell, Bertrand","philosophy",1933,10,"http://localhost:3006/assets/books/PHILOSOPHY-122.jpg" ));
    	bookRepository.save(new Book("Deceiver, The",487,"Forsyth, Frederick","fiction",1920,12,"http://localhost:3006/assets/books/FICTION-123.jpg" ));
    	bookRepository.save(new Book("Veil: Secret Wars of the CIA",536,"Woodward, Bob","history",1927,9,"http://localhost:3006/assets/books/HISTORY-124.jpg" ));
    	bookRepository.save(new Book("Char Shabda",391,"Deshpande, P L","nonfiction",1939,11,"http://localhost:3006/assets/books/NONFICTION-125.jpg" ));
    	bookRepository.save(new Book("Rosy is My Relative",346,"Durrell, Gerald","fiction",1976,11,"http://localhost:3006/assets/books/FICTION-126.jpg" ));
    	bookRepository.save(new Book("Moon and Sixpence, The",167,"Maugham, William S","fiction",1929,12,"http://localhost:3006/assets/books/FICTION-127.jpg" ));
    	bookRepository.save(new Book("Short History of the World, A",290,"Wells, H G","history",1929,9,"http://localhost:3006/assets/books/HISTORY-128.jpg" ));
    	bookRepository.save(new Book("Trembling of a Leaf, The",554,"Maugham, William S","fiction",1911,10,"http://localhost:3006/assets/books/FICTION-129.jpg" ));
    	bookRepository.save(new Book("Doctor on the Brain",385,"Gordon, Richard","fiction",1946,12,"http://localhost:3006/assets/books/FICTION-130.jpg" ));
    	bookRepository.save(new Book("Simpsons & Their Mathematical Secrets",429,"Singh, Simon","science",2011,12,"http://localhost:3006/assets/books/SCIENCE-131.jpg" ));
    	bookRepository.save(new Book("Pattern Classification",444,"Duda, Hart","data-science",1974,11,"http://localhost:3006/assets/books/DATA-SCIENCE-132.jpg" ));
    	bookRepository.save(new Book("From Beirut to Jerusalem",677,"Friedman, Thomas","history",2013,10,"http://localhost:3006/assets/books/HISTORY-133.jpg" ));
    	bookRepository.save(new Book("Code Book, The",309,"Singh, Simon","science",2003,10,"http://localhost:3006/assets/books/SCIENCE-134.jpg" ));
    	bookRepository.save(new Book("Age of the Warrior, The",162,"Fisk, Robert","history",1914,12,"http://localhost:3006/assets/books/HISTORY-135.jpg" ));
    	bookRepository.save(new Book("Numbers Behind Numb3rs, The",588,"Devlin, Keith","science",1916,11,"http://localhost:3006/assets/books/SCIENCE-136.jpg" ));
    	bookRepository.save(new Book("Life in Letters, A",236,"Steinbeck, John","nonfiction",1993,11,"http://localhost:3006/assets/books/NONFICTION-137.jpg" ));
    	bookRepository.save(new Book("Information, The",671,"Gleick, James","science",1950,10,"http://localhost:3006/assets/books/SCIENCE-138.jpg" ));
    	bookRepository.save(new Book("Elements of Information Theory",574,"Thomas, Joy","data-science",1978,11,"http://localhost:3006/assets/books/DATA-SCIENCE-139.jpg" ));
    	bookRepository.save(new Book("Power Electronics - Rashid",600,"Rashid, Muhammad","computer-science",1929,12,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-140.jpg" ));
    	bookRepository.save(new Book("Power Electronics - Mohan",584,"Mohan, Ned","computer-science",1953,11,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-141.jpg" ));
    	bookRepository.save(new Book("Neural Networks",241,"Haykin, Simon","data-science",2008,10,"http://localhost:3006/assets/books/DATA-SCIENCE-142.jpg" ));
    	bookRepository.save(new Book("Grapes of Wrath, The",621,"Steinbeck, John","fiction",1949,10,"http://localhost:3006/assets/books/FICTION-143.jpg" ));
    	bookRepository.save(new Book("Vyakti ani Valli",197,"Deshpande, P L","nonfiction",1976,9,"http://localhost:3006/assets/books/NONFICTION-144.jpg" ));
    	bookRepository.save(new Book("Statistical Learning Theory",180,"Vapnik, Vladimir","data-science",2012,10,"http://localhost:3006/assets/books/DATA-SCIENCE-145.jpg" ));
    	bookRepository.save(new Book("Empire of the Mughal - The Tainted Throne",342,"Rutherford, Alex","history",1999,10,"http://localhost:3006/assets/books/HISTORY-146.jpg" ));
    	bookRepository.save(new Book("Empire of the Mughal - Brothers at War",610,"Rutherford, Alex","history",1941,12,"http://localhost:3006/assets/books/HISTORY-147.jpg" ));
    	bookRepository.save(new Book("Empire of the Mughal - Ruler of the World",248,"Rutherford, Alex","history",1993,12,"http://localhost:3006/assets/books/HISTORY-148.jpg" ));
    	bookRepository.save(new Book("Empire of the Mughal - The Serpents Tooth",593,"Rutherford, Alex","history",1952,10,"http://localhost:3006/assets/books/HISTORY-149.jpg" ));
    	bookRepository.save(new Book("Empire of the Mughal - Raiders from the North",571,"Rutherford, Alex","history",1937,12,"http://localhost:3006/assets/books/HISTORY-150.jpg" ));
    	bookRepository.save(new Book("Mossad",226,"Baz-Zohar, Michael","history",1986,10,"http://localhost:3006/assets/books/HISTORY-151.jpg" ));
    	bookRepository.save(new Book("Jim Corbett Omnibus",335,"Corbett, Jim","nonfiction",1921,10,"http://localhost:3006/assets/books/NONFICTION-152.jpg" ));
    	bookRepository.save(new Book("20000 Leagues Under the Sea",451,"Verne, Jules","fiction",1950,10,"http://localhost:3006/assets/books/FICTION-153.jpg" ));
    	bookRepository.save(new Book("Batatyachi Chal",301,"Deshpande P L","fiction",1995,9,"http://localhost:3006/assets/books/FICTION-154.jpg" ));
    	bookRepository.save(new Book("Hafasavnuk",364,"Deshpande P L","fiction",1953,9,"http://localhost:3006/assets/books/FICTION-155.jpg" ));
    	bookRepository.save(new Book("Urlasurla",141,"Deshpande P L","fiction",1949,12,"http://localhost:3006/assets/books/FICTION-156.jpg" ));
    	bookRepository.save(new Book("Pointers in C",178,"Kanetkar, Yashwant","computer-science",1958,12,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-157.jpg" ));
    	bookRepository.save(new Book("Cathedral and the Bazaar, The",307,"Raymond, Eric","computer-science",1949,12,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-158.jpg" ));
    	bookRepository.save(new Book("Design with OpAmps",368,"Franco, Sergio","computer-science",1950,10,"http://localhost:3006/assets/books/COMPUTER-SCIENCE-159.jpg" ));
    	bookRepository.save(new Book("Think Complexity",229,"Downey, Allen","data-science",1976,9,"http://localhost:3006/assets/books/DATA-SCIENCE-160.jpg" ));
    	bookRepository.save(new Book("Devils Advocate, The",243,"West, Morris","fiction",1968,10,"http://localhost:3006/assets/books/FICTION-161.jpg" ));
    	bookRepository.save(new Book("Ayn Rand Answers",626,"Rand, Ayn","philosophy",1944,9,"http://localhost:3006/assets/books/PHILOSOPHY-162.jpg" ));
    	bookRepository.save(new Book("Philosophy: Who Needs It",539,"Rand, Ayn","philosophy",1901,9,"http://localhost:3006/assets/books/PHILOSOPHY-163.jpg" ));
    	bookRepository.save(new Book("Data Analysis with Open Source Tools",152,"Janert, Phillip","data-science",1977,11,"http://localhost:3006/assets/books/DATA-SCIENCE-164.jpg" ));
    	bookRepository.save(new Book("Brocas Brain",255,"Sagan, Carl","science",1990,11,"http://localhost:3006/assets/books/SCIENCE-165.jpg" ));
    	bookRepository.save(new Book("Men of Mathematics",402,"Bell, E T","mathematics",1975,11,"http://localhost:3006/assets/books/MATHEMATICS-166.jpg" ));
    	bookRepository.save(new Book("Oxford book of Modern Science Writing",374,"Dawkins, Richard","science",1938,9,"http://localhost:3006/assets/books/SCIENCE-167.jpg" ));
    	bookRepository.save(new Book("Justice, Judiciary and Democracy",283,"Ranjan, Sudhanshu","philosophy",1984,9,"http://localhost:3006/assets/books/PHILOSOPHY-168.jpg" ));
    	bookRepository.save(new Book("Arthashastra, The",403,"Kautiyla","philosophy",1947,10,"http://localhost:3006/assets/books/PHILOSOPHY-169.jpg" ));
    	bookRepository.save(new Book("We the People",279,"Palkhivala","philosophy",1936,9,"http://localhost:3006/assets/books/PHILOSOPHY-170.jpg" ));
    	bookRepository.save(new Book("We the Nation",160,"Palkhivala","philosophy",1936,9,"http://localhost:3006/assets/books/PHILOSOPHY-171.jpg" ));
    	bookRepository.save(new Book("Courtroom Genius, The",530,"Sorabjee","nonfiction",1959,10,"http://localhost:3006/assets/books/NONFICTION-172.jpg" ));
    	bookRepository.save(new Book("Dongri to Dubai",259,"Zaidi, Hussain","nonfiction",1979,9,"http://localhost:3006/assets/books/NONFICTION-173.jpg" ));
    	bookRepository.save(new Book("History of England, Foundation",129,"Ackroyd, Peter","history",1979,11,"http://localhost:3006/assets/books/HISTORY-174.jpg" ));
    	bookRepository.save(new Book("City of Djinns",231,"Dalrymple, William","history",1995,12,"http://localhost:3006/assets/books/HISTORY-175.jpg" ));
    	bookRepository.save(new Book("Indias Legal System",401,"Nariman","nonfiction",1984,11,"http://localhost:3006/assets/books/NONFICTION-176.jpg" ));
    	bookRepository.save(new Book("More Tears to Cry",92,"Sassoon, Jean","fiction",1979,9,"http://localhost:3006/assets/books/FICTION-177.jpg" ));
    	bookRepository.save(new Book("Ropemaker, The",499,"Dickinson, Peter","fiction",1948,11,"http://localhost:3006/assets/books/FICTION-178.jpg" ));
    	bookRepository.save(new Book("Angels & Demons",678,"Brown, Dan","fiction",1909,10,"http://localhost:3006/assets/books/FICTION-179.jpg" ));
    	bookRepository.save(new Book("Prince, The",498,"Machiavelli","philosophy",1901,9,"http://localhost:3006/assets/books/PHILOSOPHY-180.jpg" ));
    	bookRepository.save(new Book("Eyeless in Gaza",381,"Huxley, Aldous","fiction",1915,12,"http://localhost:3006/assets/books/FICTION-181.jpg" ));
    	bookRepository.save(new Book("Tales of Beedle the Bard",545,"Rowling, J K","fiction",1903,12,"http://localhost:3006/assets/books/FICTION-182.jpg" ));
    	bookRepository.save(new Book("Girl with the Dragon Tattoo",115,"Larsson, Steig","fiction",1962,10,"http://localhost:3006/assets/books/FICTION-183.jpg" ));
    	bookRepository.save(new Book("Girl who kicked the Hornets Nest",327,"Larsson, Steig","fiction",1921,12,"http://localhost:3006/assets/books/FICTION-184.jpg" ));
    	bookRepository.save(new Book("Girl who played with Fire",621,"Larsson, Steig","fiction",1952,10,"http://localhost:3006/assets/books/FICTION-185.jpg" ));
    	bookRepository.save(new Book("Structure and Randomness",376,"Tao, Terence","mathematics",1999,12,"http://localhost:3006/assets/books/MATHEMATICS-186.jpg" ));
    	bookRepository.save(new Book("Image Processing with MATLAB",153,"Eddins, Steve","signal-processing",2004,11,"http://localhost:3006/assets/books/SIGNAL-PROCESSING-187.jpg" ));
    	bookRepository.save(new Book("Animal Farm",265,"Orwell, George","fiction",1977,11,"http://localhost:3006/assets/books/FICTION-188.jpg" ));
    	bookRepository.save(new Book("Idiot, The",153,"Dostoevsky, Fyodor","fiction",1986,10,"http://localhost:3006/assets/books/FICTION-189.jpg" ));
    	bookRepository.save(new Book("Christmas Carol, A",455,"Dickens, Charles","fiction",1919,10,"http://localhost:3006/assets/books/FICTION-190.jpg" ));

    
      };
   }
	
}
